上古漢語：增加金理新擬音
laubonghaudoi/Chinese_Rime pull request #30
Opened 2024-01-08 05:20 UTC by Hulenkius

2024-01-08 06:13 UTC, laubonghaudoi commented
@Hulenkius 除了`/script` 之外，還要在 `/download` 加入下載版，還有在 `/sources` 加入 submodule

2024-01-08 06:15 UTC, laubonghaudoi requested changes
感謝提交，麻煩加入源文件到 `/download` 和 submodule 到 `/sources`

2024-01-08 09:28 UTC, Hulenkius commented
已作相關更改

2024-01-09 22:45 UTC, laubonghaudoi commented
@Hulenkius 這個方案有配方化嗎？好像找不到 repo

2024-01-09 22:47 UTC, laubonghaudoi commented
哦找到了，在這裏 https://github.com/Hulenkius/RIME_OC_collections

2024-01-09 22:47 UTC, laubonghaudoi approved these changes

2024-01-09 22:47 UTC, merged